# Configuration for https://github.com/apps/settings

repository:
  private: false
  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: false
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false
  allow_auto_merge: true
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true
  web_commit_signoff_required: true

labels:
  - name: bug
    color: "#d73a4a"
    description: Something isn't working
  - name: feature
    color: "#93E04B"
    description: New functionality
  - name: chore
    color: "#47C1D0"
    description: Some annoying work...
  - name: dependency
    color: "#fbca04"
    description: Dependabot doing its job

branches:
  - name: main
    protection:
      allow_deletion: false
      allow_force_pushes: false
      enforce_admins: true
      lock_branch: false
      required_conversation_resolution: true
      required_linear_history: true
      required_signatures: true
      required_pull_request_reviews: null
      required_status_checks:
        strict: false
        contexts:
          - merge-gatekeeper
      restrictions: null
